@isTest
private class demoUnitTest {
 @isTest
    static void Testcolor(){
         set<Integer> ac=new set<Integer>();
            ac.add(5);
            ac.add(9);
            ac.add(5);
            ac.add(9);
            system.debug('Elements are: '+ac);
            Integer size_ac=ac.size();
        Test.startTest();
       demo.addint();
        demo.colour();
        Test.stopTest();
    }
}