public class demo {
    public static void addint()
        {
            set<Integer> ac=new set<Integer>();
            ac.add(5);
            ac.add(9);
            ac.add(5);
            ac.add(9);
            system.debug('Elements are: '+ac);
            Integer size_ac=ac.size();
            system.debug(size_ac);
        }
    public static void colour()
    {
        map<integer,string> col = new map<integer,string>();
        col.put(1,'red');
         col.put(2,'black');
         col.put(3,'blue');
      system.debug(col);
    }
  
    }